using Cx.Compiler;
using Cx.Compiler.Semantic;
using Cx.Compiler.Syntax.Nodes;

namespace Cx.Compiler.C;

internal sealed class CxToCTranslationUnitLowerer(
    CNameManglerOptions? nameManglerOptions = null)
{
    public CTranslationUnit Lower(ProgramNode program)
    {
        var backend = CBackendContext.Create(
            program,
            program.TypeAdapters,
            nameManglerOptions);
        var items = new List<CTranslationUnitItem>
        {
            new CComment("generated by Cx.Compiler"),
            new CBlankLine(),
        };

        var includes = CIncludeCollector.Collect(program);
        foreach (var include in includes)
        {
            items.Add(include);
        }

        if (includes.Count > 0)
        {
            items.Add(new CBlankLine());
        }

        foreach (var externFunction in program.ExternFunctions)
        {
            items.Add(CDeclarationBuilder.BuildFunctionDeclaration(backend, externFunction));
        }

        if (program.ExternFunctions.Count > 0)
        {
            items.Add(new CBlankLine());
        }

        var declarationOrder = CDeclarationOrderPlanner.Plan(backend, program);

        foreach (var typeAlias in declarationOrder.EarlyTypeAliases)
        {
            items.Add(CDeclarationBuilder.BuildTypeAlias(backend, typeAlias));
        }

        if (declarationOrder.EarlyTypeAliases.Count > 0)
        {
            items.Add(new CBlankLine());
        }

        var enumNameLowerer = new ImportedNameLowerer(backend);
        foreach (var enumNode in program.Enums.Where(enumNode => !enumNode.IsDataEnum))
        {
            items.Add(CDeclarationBuilder.BuildEnum(enumNode));
            items.Add(new CBlankLine());
        }

        foreach (var structNode in declarationOrder.EarlyStructs)
        {
            items.Add(CDeclarationBuilder.BuildStruct(backend, structNode));
            items.Add(new CBlankLine());
        }

        var dataEnumDeclarations = program.Enums
            .Where(enumNode => enumNode.IsDataEnum)
            .Select(enumNode => CDeclarationBuilder.BuildDataEnum(backend, enumNode, enumNameLowerer))
            .ToList();
        foreach (var dataEnum in dataEnumDeclarations)
        {
            items.Add(dataEnum);
            items.Add(new CBlankLine());
        }

        var interfaceImplementations = program.Structs
            .SelectMany(structNode =>
                structNode.Semantic.CoreInterfaceImplementations)
            .GroupBy(
                implementation => (
                    implementation.Struct.Name,
                    implementation.Interface.Name))
            .Select(group => group.First())
            .ToList();
        if (program.Interfaces.Count > 0)
        {
            items.Add(CInterfaceDeclarationBuilder.BuildTypeIdEnum(backend, interfaceImplementations));
            items.Add(new CBlankLine());
        }

        foreach (var interfaceNode in program.Interfaces)
        {
            items.Add(CInterfaceDeclarationBuilder.BuildVTableStruct(backend, interfaceNode));
            items.Add(new CBlankLine());
            items.Add(CInterfaceDeclarationBuilder.BuildValueStruct(backend, interfaceNode));
            items.Add(new CBlankLine());
        }

        foreach (var taggedUnion in program.TaggedUnions)
        {
            items.Add(CTaggedUnionDeclarationBuilder.Build(backend, taggedUnion));
            items.Add(new CBlankLine());
        }

        foreach (var structNode in declarationOrder.LateStructs)
        {
            items.Add(CDeclarationBuilder.BuildStruct(backend, structNode));
            items.Add(new CBlankLine());
        }

        foreach (var typeAlias in declarationOrder.LateTypeAliases)
        {
            items.Add(CDeclarationBuilder.BuildTypeAlias(backend, typeAlias));
        }

        if (declarationOrder.LateTypeAliases.Count > 0)
        {
            items.Add(new CBlankLine());
        }

        var nameLowerer = new ImportedNameLowerer(backend);

        foreach (var implementation in interfaceImplementations)
        {
            items.Add(CInterfaceDeclarationBuilder.BuildVTableDeclaration(backend, implementation));
        }

        if (interfaceImplementations.Count > 0)
        {
            items.Add(new CBlankLine());
        }

        foreach (var global in program.GlobalVariables)
        {
            items.Add(CDeclarationBuilder.BuildGlobalDeclaration(backend, global, nameLowerer));
        }

        if (program.GlobalVariables.Count > 0)
        {
            items.Add(new CBlankLine());
        }

        foreach (var function in program.Functions)
        {
            items.Add(CDeclarationBuilder.BuildFunctionDeclaration(backend, function));
        }

        if (program.Functions.Count > 0)
        {
            items.Add(new CBlankLine());
        }

        foreach (var dataEnum in dataEnumDeclarations)
        {
            items.Add(new CDataEnumTableDeclaration(dataEnum));
            items.Add(new CBlankLine());
        }

        foreach (var implementation in interfaceImplementations)
        {
            items.Add(CInterfaceDeclarationBuilder.BuildVTableInstance(
                backend,
                implementation));
            items.Add(new CBlankLine());
        }

        foreach (var function in program.Functions)
        {
            items.Add(CDeclarationBuilder.BuildFunctionDefinition(function, nameLowerer.ForFunction(function)));
            items.Add(new CBlankLine());
        }

        return new CTranslationUnit(items);
    }
}
