using Cx.Compiler;
using Cx.Compiler.Semantic;
using Cx.Compiler.Syntax.Nodes;

namespace Cx.Compiler.C;

internal sealed class CxToCTranslationUnitLowerer(CNameManglerOptions? nameManglerOptions = null)
{
    public CTranslationUnit Lower(ProgramNode program)
    {
        var typeRefParser = new TypeRefParser(program);
        var backend = CBackendContext.Create(program.TypeAdapters, nameManglerOptions, typeRefParser);
        var items = new List<CTranslationUnitItem>
        {
            new CComment("generated by Cx.Compiler"),
            new CBlankLine(),
        };

        var functionsToEmit = CEmitSelection.GetFunctionsToEmit(program);
        var emitProgram = program with { Functions = functionsToEmit };
        var includes = CIncludeCollector.Collect(program, emitProgram);
        foreach (var include in includes)
        {
            items.Add(include);
        }

        if (includes.Count > 0)
        {
            items.Add(new CBlankLine());
        }

        foreach (var externFunction in program.ExternFunctions.Where(function => !function.IsHeaderDeclaration))
        {
            items.Add(CDeclarationBuilder.BuildFunctionDeclaration(backend, externFunction));
        }

        if (program.ExternFunctions.Any(function => !function.IsHeaderDeclaration))
        {
            items.Add(new CBlankLine());
        }

        var structsToEmit = CEmitSelection.GetStructsToEmit(emitProgram);
        var declarationOrder = CDeclarationOrderPlanner.Plan(backend, program, emitProgram, structsToEmit);

        foreach (var typeAlias in declarationOrder.EarlyTypeAliases)
        {
            items.Add(CDeclarationBuilder.BuildTypeAlias(backend, typeAlias));
        }

        if (declarationOrder.EarlyTypeAliases.Count > 0)
        {
            items.Add(new CBlankLine());
        }

        foreach (var enumNode in emitProgram.Enums.Where(enumNode => !enumNode.IsHeaderDeclaration))
        {
            items.Add(CDeclarationBuilder.BuildEnum(enumNode));
            items.Add(new CBlankLine());
        }

        var interfaceImplementations = CInterfaceImplementationCollector.Collect(emitProgram, structsToEmit);
        if (emitProgram.Interfaces.Count > 0)
        {
            items.Add(CInterfaceDeclarationBuilder.BuildTypeIdEnum(backend, interfaceImplementations));
            items.Add(new CBlankLine());
        }

        foreach (var interfaceNode in emitProgram.Interfaces)
        {
            items.Add(CInterfaceDeclarationBuilder.BuildVTableStruct(backend, interfaceNode));
            items.Add(new CBlankLine());
            items.Add(CInterfaceDeclarationBuilder.BuildValueStruct(backend, interfaceNode));
            items.Add(new CBlankLine());
        }

        foreach (var structNode in declarationOrder.EarlyStructs)
        {
            items.Add(CDeclarationBuilder.BuildStruct(backend, structNode));
            items.Add(new CBlankLine());
        }

        foreach (var taggedUnion in emitProgram.TaggedUnions.Where(union => !union.IsHeaderDeclaration))
        {
            items.Add(CTaggedUnionDeclarationBuilder.Build(backend, taggedUnion));
            items.Add(new CBlankLine());
        }

        foreach (var structNode in declarationOrder.LateStructs)
        {
            items.Add(CDeclarationBuilder.BuildStruct(backend, structNode));
            items.Add(new CBlankLine());
        }

        foreach (var typeAlias in declarationOrder.LateTypeAliases)
        {
            items.Add(CDeclarationBuilder.BuildTypeAlias(backend, typeAlias));
        }

        if (declarationOrder.LateTypeAliases.Count > 0)
        {
            items.Add(new CBlankLine());
        }

        var nameLowerer = new ImportedNameLowerer(emitProgram, structsToEmit, backend);

        foreach (var implementation in interfaceImplementations)
        {
            items.Add(CInterfaceDeclarationBuilder.BuildVTableDeclaration(backend, implementation));
        }

        if (interfaceImplementations.Count > 0)
        {
            items.Add(new CBlankLine());
        }

        foreach (var global in emitProgram.GlobalVariables.Where(global => !global.IsHeaderDeclaration))
        {
            items.Add(CDeclarationBuilder.BuildGlobalDeclaration(backend, global, nameLowerer));
        }

        if (emitProgram.GlobalVariables.Any(global => !global.IsHeaderDeclaration))
        {
            items.Add(new CBlankLine());
        }

        foreach (var function in functionsToEmit)
        {
            items.Add(CDeclarationBuilder.BuildFunctionDeclaration(backend, function));
        }

        if (program.Functions.Count > 0)
        {
            items.Add(new CBlankLine());
        }

        foreach (var implementation in interfaceImplementations)
        {
            items.Add(CInterfaceDeclarationBuilder.BuildVTableInstance(backend, implementation, functionsToEmit));
            items.Add(new CBlankLine());
        }

        foreach (var function in functionsToEmit)
        {
            items.Add(CDeclarationBuilder.BuildFunctionDefinition(function, nameLowerer.ForFunction(function)));
            items.Add(new CBlankLine());
        }

        return new CTranslationUnit(items);
    }
}
