using Cx.Compiler;
using Cx.Compiler.Semantic;
using Cx.Compiler.Syntax.Nodes;

namespace Cx.Compiler.C;

internal sealed class CxToCTranslationUnitLowerer(CNameManglerOptions? nameManglerOptions = null)
{
    public CTranslationUnit Lower(ProgramNode program)
    {
        var typeRefParser = new TypeRefParser(program);
        var backend = CBackendContext.Create(program.TypeAdapters, nameManglerOptions, typeRefParser);
        var items = new List<CTranslationUnitItem>
        {
            new CComment("generated by Cx.Compiler"),
            new CBlankLine(),
        };

        var functionsToEmit = CEmitSelection.GetFunctionsToEmit(program);
        var emitProgram = program with { Functions = functionsToEmit };
        var includes = program.Includes
            .Concat(CDeclarationUsageAnalyzer.GetDeclarationsToInclude(emitProgram)
                .Select(declaration => new IncludeNode(declaration.Location, declaration.HeaderPath, declaration.IsSystemHeader)))
            .DistinctBy(include => (include.Path, include.IsSystem))
            .ToList();
        var usesNull = CNullUsageAnalyzer.UsesNull(emitProgram);
        if (usesNull && !includes.Any(include => include.IsSystem && include.Path == "stddef.h"))
        {
            items.Add(new CInclude("stddef.h", IsSystem: true));
        }

        foreach (var include in includes)
        {
            items.Add(new CInclude(include.Path, include.IsSystem));
        }

        if (includes.Count > 0 || usesNull)
        {
            items.Add(new CBlankLine());
        }

        foreach (var externFunction in program.ExternFunctions.Where(function => !function.IsHeaderDeclaration))
        {
            items.Add(CDeclarationBuilder.BuildFunctionDeclaration(backend, externFunction));
        }

        if (program.ExternFunctions.Any(function => !function.IsHeaderDeclaration))
        {
            items.Add(new CBlankLine());
        }

        var structsToEmit = CEmitSelection.GetStructsToEmit(emitProgram);
        var compositeTypeNames = structsToEmit
            .Select(structNode => structNode.Name)
            .Concat(emitProgram.TaggedUnions.Where(union => !union.IsHeaderDeclaration).Select(taggedUnion => taggedUnion.Name))
            .ToHashSet(StringComparer.Ordinal);
        var emittedTypeAliases = program.TypeAliases
            .Where(typeAlias => !typeAlias.IsHeaderDeclaration)
            .ToList();
        var earlyTypeAliases = emittedTypeAliases
            .Where(typeAlias => !CTypeLowerer.ReferencesCompositeType(CTypeText.TypeAliasTargetTypeText(typeAlias), compositeTypeNames, backend.TypeAdapters))
            .ToList();
        var lateTypeAliases = emittedTypeAliases
            .Where(typeAlias => CTypeLowerer.ReferencesCompositeType(CTypeText.TypeAliasTargetTypeText(typeAlias), compositeTypeNames, backend.TypeAdapters))
            .ToList();

        foreach (var typeAlias in earlyTypeAliases)
        {
            items.Add(CDeclarationBuilder.BuildTypeAlias(backend, typeAlias));
        }

        if (earlyTypeAliases.Count > 0)
        {
            items.Add(new CBlankLine());
        }

        foreach (var enumNode in emitProgram.Enums.Where(enumNode => !enumNode.IsHeaderDeclaration))
        {
            items.Add(CDeclarationBuilder.BuildEnum(enumNode));
            items.Add(new CBlankLine());
        }

        var interfaceImplementations = CInterfaceImplementationCollector.Collect(emitProgram, structsToEmit);
        if (emitProgram.Interfaces.Count > 0)
        {
            items.Add(CInterfaceDeclarationBuilder.BuildTypeIdEnum(backend, interfaceImplementations));
            items.Add(new CBlankLine());
        }

        foreach (var interfaceNode in emitProgram.Interfaces)
        {
            items.Add(CInterfaceDeclarationBuilder.BuildVTableStruct(backend, interfaceNode));
            items.Add(new CBlankLine());
            items.Add(CInterfaceDeclarationBuilder.BuildValueStruct(backend, interfaceNode));
            items.Add(new CBlankLine());
        }

        var taggedUnionNames = emitProgram.TaggedUnions
            .Where(union => !union.IsRaw)
            .Select(taggedUnion => taggedUnion.Name)
            .ToHashSet(StringComparer.Ordinal);
        var lateStructNames = structsToEmit
            .Where(structNode => structNode.Fields.Any(field => CTypeLowerer.ReferencesCompositeType(CTypeText.StructFieldTypeText(field), taggedUnionNames, backend.TypeAdapters)))
            .Select(structNode => structNode.Name)
            .ToHashSet(StringComparer.Ordinal);
        var changed = true;
        while (changed)
        {
            changed = false;
            foreach (var structNode in structsToEmit)
            {
                if (lateStructNames.Contains(structNode.Name)
                    || !structNode.Fields.Any(field => CTypeLowerer.ReferencesCompositeType(CTypeText.StructFieldTypeText(field), lateStructNames, backend.TypeAdapters)))
                {
                    continue;
                }

                lateStructNames.Add(structNode.Name);
                changed = true;
            }
        }

        var earlyStructs = CStructDependencyOrderer.OrderByFieldDependencies(
            backend,
            structsToEmit.Where(structNode => !lateStructNames.Contains(structNode.Name)).ToList());
        var lateStructs = CStructDependencyOrderer.OrderByFieldDependencies(
            backend,
            structsToEmit.Where(structNode => lateStructNames.Contains(structNode.Name)).ToList());

        foreach (var structNode in earlyStructs)
        {
            items.Add(CDeclarationBuilder.BuildStruct(backend, structNode));
            items.Add(new CBlankLine());
        }

        foreach (var taggedUnion in emitProgram.TaggedUnions.Where(union => !union.IsHeaderDeclaration))
        {
            items.Add(CTaggedUnionDeclarationBuilder.Build(backend, taggedUnion));
            items.Add(new CBlankLine());
        }

        foreach (var structNode in lateStructs)
        {
            items.Add(CDeclarationBuilder.BuildStruct(backend, structNode));
            items.Add(new CBlankLine());
        }

        foreach (var typeAlias in lateTypeAliases)
        {
            items.Add(CDeclarationBuilder.BuildTypeAlias(backend, typeAlias));
        }

        if (lateTypeAliases.Count > 0)
        {
            items.Add(new CBlankLine());
        }

        var nameLowerer = new ImportedNameLowerer(emitProgram, structsToEmit, backend);

        foreach (var implementation in interfaceImplementations)
        {
            items.Add(CInterfaceDeclarationBuilder.BuildVTableDeclaration(backend, implementation));
        }

        if (interfaceImplementations.Count > 0)
        {
            items.Add(new CBlankLine());
        }

        foreach (var global in emitProgram.GlobalVariables.Where(global => !global.IsHeaderDeclaration))
        {
            items.Add(CDeclarationBuilder.BuildGlobalDeclaration(backend, global, nameLowerer));
        }

        if (emitProgram.GlobalVariables.Any(global => !global.IsHeaderDeclaration))
        {
            items.Add(new CBlankLine());
        }

        foreach (var function in functionsToEmit)
        {
            items.Add(CDeclarationBuilder.BuildFunctionDeclaration(backend, function));
        }

        if (program.Functions.Count > 0)
        {
            items.Add(new CBlankLine());
        }

        foreach (var implementation in interfaceImplementations)
        {
            items.Add(CInterfaceDeclarationBuilder.BuildVTableInstance(backend, implementation, functionsToEmit));
            items.Add(new CBlankLine());
        }

        foreach (var function in functionsToEmit)
        {
            items.Add(CDeclarationBuilder.BuildFunctionDefinition(function, nameLowerer.ForFunction(function)));
            items.Add(new CBlankLine());
        }

        return new CTranslationUnit(items);
    }
}
