using System.Text.RegularExpressions;
using Cx.Compiler.C;
using Cx.Compiler.Semantic;
using Cx.Compiler.Syntax.Nodes;

namespace Cx.Compiler;

public sealed partial class CEmitter
{
    private static IReadOnlyList<TypeAdapterNode> s_typeAdapters = [];
    private static CAbiNameService s_abiNames = new(s_typeAdapters);
    private static CNameMangler s_nameMangler = CreateNameMangler();
    private static TypeRefParser? s_typeRefParser;

    public CEmitter()
        : this(null)
    {
    }

    internal CEmitter(CNameManglerOptions? nameManglerOptions)
    {
        s_nameMangler = CreateNameMangler(nameManglerOptions);
    }

    public string Emit(ProgramNode program) =>
        Emit(new CxToCTranslationUnitLowerer(s_nameMangler.Options).Lower(program));

    internal string Emit(CTranslationUnit unit) =>
        new CTranslationUnitEmitter().Emit(unit);

    internal CTranslationUnit LowerToC(ProgramNode program)
    {
        s_typeAdapters = program.TypeAdapters;
        s_abiNames = new CAbiNameService(s_typeAdapters);
        s_nameMangler = CreateNameMangler(s_nameMangler.Options);
        var typeRefParser = new TypeRefParser(program);
        s_typeRefParser = typeRefParser;
        var items = new List<CTranslationUnitItem>
        {
            new CComment("generated by Cx.Compiler"),
            new CBlankLine(),
        };

        var functionsToEmit = GetFunctionsToEmit(program);
        var emitProgram = program with { Functions = functionsToEmit };
        var includes = program.Includes
            .Concat(GetCDeclarationsToInclude(emitProgram)
                .Select(declaration => new IncludeNode(declaration.Location, declaration.HeaderPath, declaration.IsSystemHeader)))
            .DistinctBy(include => (include.Path, include.IsSystem))
            .ToList();
        var usesNull = CNullUsageAnalyzer.UsesNull(emitProgram);
        if (usesNull && !includes.Any(include => include.IsSystem && include.Path == "stddef.h"))
        {
            items.Add(new CInclude("stddef.h", IsSystem: true));
        }

        foreach (var include in includes)
        {
            items.Add(new CInclude(include.Path, include.IsSystem));
        }

        if (includes.Count > 0 || usesNull)
        {
            items.Add(new CBlankLine());
        }

        foreach (var externFunction in program.ExternFunctions.Where(function => !function.IsHeaderDeclaration))
        {
            items.Add(ToCFunctionDeclaration(externFunction));
        }

        if (program.ExternFunctions.Any(function => !function.IsHeaderDeclaration))
        {
            items.Add(new CBlankLine());
        }

        var structsToEmit = GetStructsToEmit(emitProgram);
        var compositeTypeNames = structsToEmit
            .Select(structNode => structNode.Name)
            .Concat(emitProgram.TaggedUnions.Where(union => !union.IsHeaderDeclaration).Select(taggedUnion => taggedUnion.Name))
            .ToHashSet(StringComparer.Ordinal);
        var emittedTypeAliases = program.TypeAliases
            .Where(typeAlias => !typeAlias.IsHeaderDeclaration)
            .ToList();
        var earlyTypeAliases = emittedTypeAliases
            .Where(typeAlias => !ReferencesCompositeType(TypeAliasTargetTypeText(typeAlias), compositeTypeNames))
            .ToList();
        var lateTypeAliases = emittedTypeAliases
            .Where(typeAlias => ReferencesCompositeType(TypeAliasTargetTypeText(typeAlias), compositeTypeNames))
            .ToList();

        foreach (var typeAlias in earlyTypeAliases)
        {
            items.Add(ToCTypeAlias(typeAlias, typeRefParser));
        }

        if (earlyTypeAliases.Count > 0)
        {
            items.Add(new CBlankLine());
        }

        foreach (var enumNode in emitProgram.Enums.Where(enumNode => !enumNode.IsHeaderDeclaration))
        {
            items.Add(ToCEnum(enumNode));
            items.Add(new CBlankLine());
        }

        var interfaceImplementations = GetInterfaceImplementations(emitProgram, structsToEmit);
        if (emitProgram.Interfaces.Count > 0)
        {
            items.Add(ToCTypeIdEnum(interfaceImplementations));
            items.Add(new CBlankLine());
        }

        foreach (var interfaceNode in emitProgram.Interfaces)
        {
            items.Add(ToCInterfaceVTableStruct(interfaceNode));
            items.Add(new CBlankLine());
            items.Add(ToCInterfaceValueStruct(interfaceNode));
            items.Add(new CBlankLine());
        }

        var taggedUnionNames = emitProgram.TaggedUnions
            .Where(union => !union.IsRaw)
            .Select(taggedUnion => taggedUnion.Name)
            .ToHashSet(StringComparer.Ordinal);
        var lateStructNames = structsToEmit
            .Where(structNode => structNode.Fields.Any(field => ReferencesCompositeType(StructFieldTypeText(field), taggedUnionNames)))
            .Select(structNode => structNode.Name)
            .ToHashSet(StringComparer.Ordinal);
        var changed = true;
        while (changed)
        {
            changed = false;
            foreach (var structNode in structsToEmit)
            {
                if (lateStructNames.Contains(structNode.Name)
                    || !structNode.Fields.Any(field => ReferencesCompositeType(StructFieldTypeText(field), lateStructNames)))
                {
                    continue;
                }

                lateStructNames.Add(structNode.Name);
                changed = true;
            }
        }

        var earlyStructs = OrderStructsByFieldDependencies(
            structsToEmit.Where(structNode => !lateStructNames.Contains(structNode.Name)).ToList());
        var lateStructs = OrderStructsByFieldDependencies(
            structsToEmit.Where(structNode => lateStructNames.Contains(structNode.Name)).ToList());

        foreach (var structNode in earlyStructs)
        {
            items.Add(ToCStruct(structNode));
            items.Add(new CBlankLine());
        }

        foreach (var taggedUnion in emitProgram.TaggedUnions.Where(union => !union.IsHeaderDeclaration))
        {
            items.Add(ToCTaggedUnion(taggedUnion));
            items.Add(new CBlankLine());
        }

        foreach (var structNode in lateStructs)
        {
            items.Add(ToCStruct(structNode));
            items.Add(new CBlankLine());
        }

        foreach (var typeAlias in lateTypeAliases)
        {
            items.Add(ToCTypeAlias(typeAlias, typeRefParser));
        }

        if (lateTypeAliases.Count > 0)
        {
            items.Add(new CBlankLine());
        }

        var nameLowerer = new ImportedNameLowerer(emitProgram, structsToEmit);

        foreach (var implementation in interfaceImplementations)
        {
            items.Add(ToCInterfaceVTableDeclaration(implementation));
        }

        if (interfaceImplementations.Count > 0)
        {
            items.Add(new CBlankLine());
        }

        foreach (var global in emitProgram.GlobalVariables.Where(global => !global.IsHeaderDeclaration))
        {
            items.Add(ToCGlobalDeclaration(global, nameLowerer));
        }

        if (emitProgram.GlobalVariables.Any(global => !global.IsHeaderDeclaration))
        {
            items.Add(new CBlankLine());
        }

        foreach (var function in functionsToEmit)
        {
            items.Add(ToCFunctionDeclaration(function));
        }

        if (program.Functions.Count > 0)
        {
            items.Add(new CBlankLine());
        }

        foreach (var implementation in interfaceImplementations)
        {
            items.Add(ToCInterfaceVTableInstance(implementation, functionsToEmit));
            items.Add(new CBlankLine());
        }

        foreach (var function in functionsToEmit)
        {
            items.Add(ToCFunctionDefinition(function, nameLowerer.ForFunction(function)));
            items.Add(new CBlankLine());
        }

        return new CTranslationUnit(items);
    }

    private static CNameMangler CreateNameMangler(CNameManglerOptions? options = null) =>
        new(
            type => s_abiNames.LowerType(type),
            s_abiNames.SanitizeTypeName,
            options);

    private static CEnumDeclaration ToCEnum(EnumNode enumNode) =>
        new(
            enumNode.Name,
            enumNode.Members
                .Select(member => new CEnumMember(member.Name, member.Value))
                .ToList());

    private static CStructDeclaration ToCStruct(StructNode structNode) =>
        new(
            structNode.Name,
            structNode.Fields
                .Select(field => LowerStructFieldDeclaration(structNode, field))
                .ToList());

    private static CTaggedUnionDeclaration ToCTaggedUnion(TaggedUnionNode taggedUnion) =>
        new(
            taggedUnion.Name,
            taggedUnion.IsRaw,
            taggedUnion.Variants
                .Select(variant =>
                {
                    var variantType = TaggedUnionVariantTypeText(variant);
                    return new CTaggedUnionVariantDeclaration(
                        variant.Name,
                        LowerFieldType(variant.TypeNode, variantType),
                        LowerField(variant.TypeNode, variantType, variant.Name));
                })
                .ToList());

    private static CTypeAliasDeclaration ToCTypeAlias(TypeAliasNode typeAlias, TypeRefParser typeRefParser)
    {
        var targetRef = typeAlias.TargetTypeNode?.Semantic.Type
            ?? typeRefParser.Parse(typeAlias.TargetTypeNode);
        if (targetRef is not TypeRef.Unknown)
        {
            return new CTypeAliasDeclaration(
                typeAlias.Name,
                s_abiNames.LowerTypeRef(targetRef));
        }

        throw CEmissionGuards.UnresolvedTypeAlias(typeAlias);
    }

    private static CFunctionDeclaration ToCFunctionDeclaration(FunctionNode function)
    {
        var selfType = ResolveSelfType(function);
        return new CFunctionDeclaration(
            new CFunctionSignature(
                LowerReturnType(function.ReturnTypeNode, FunctionReturnTypeText(function), selfType),
                GetCFunctionName(function),
                function.Parameters
                    .Select(parameter => LowerParameter(parameter, selfType))
                    .ToList()));
    }

    private static CFunctionDefinition ToCFunctionDefinition(
        FunctionNode function,
        ImportedNameLowerer nameLowerer)
    {
        var declaration = ToCFunctionDeclaration(function);
        var statementLowerer = new CStatementLoweringPipeline(nameLowerer);
        return new CFunctionDefinition(
            declaration.Signature,
            statementLowerer.LowerBlock(function.Body));
    }

    private static CFunctionDeclaration ToCFunctionDeclaration(ExternFunctionNode function) =>
        new(
            new CFunctionSignature(
                LowerReturnType(function.ReturnTypeNode, ExternFunctionReturnTypeText(function)),
                function.Name,
                function.Parameters
                    .Select(parameter => LowerParameter(parameter))
                    .ToList()));

    private static CGlobalDeclaration ToCGlobalDeclaration(
        GlobalVariableNode global,
        ImportedNameLowerer nameLowerer)
    {
        var globalType = GlobalVariableTypeText(global);
        return new CGlobalDeclaration(
            LowerVariable(global.TypeNode, globalType, global.Name, global.IsConst),
            LowerGlobalInitializer(global, globalType, nameLowerer));
    }

    private static CExpression? LowerGlobalInitializer(
        GlobalVariableNode global,
        string fallbackType,
        ImportedNameLowerer nameLowerer) =>
        global.Initializer is null
            ? null
            : global.TypeNode?.Semantic.Type is { } typeRef
                ? nameLowerer.LowerInitializerExpression(typeRef, global.Initializer)
                : nameLowerer.LowerInitializerExpression(fallbackType, global.Initializer);

    private static CFieldDeclaration LowerStructFieldDeclaration(StructNode structNode, StructFieldNode field)
    {
        var selfPointerType = structNode.Name + "*";
        var fieldType = StructFieldTypeText(field);
        return fieldType == selfPointerType
            ? new CFieldDeclaration(
                new CPointerTypeRef(new CStructTypeRef(structNode.Name)),
                field.Name)
            : LowerField(field.TypeNode, fieldType, field.Name);
    }


    private static IReadOnlyList<FunctionNode> GetFunctionsToEmit(ProgramNode program)
    =>
        program.Functions
            .Where(function => function.TypeParameters.Count == 0)
            .ToList();

    private static string SubstituteAdapterBaseType(TypeAdapterNode adapter, IReadOnlyList<string> receiverArguments)
    {
        if (adapter.TypeParameters.Count == 0 || adapter.TypeParameters.Count != receiverArguments.Count)
        {
            return TypeAdapterBaseTypeText(adapter);
        }

        var substitutions = adapter.TypeParameters
            .Zip(receiverArguments)
            .ToDictionary(pair => pair.First, pair => pair.Second, StringComparer.Ordinal);
        return SubstituteGenericType(TypeAdapterBaseTypeText(adapter), substitutions);
    }


    private static IReadOnlyList<StructNode> GetStructsToEmit(ProgramNode program)
    =>
        program.Structs
            .Where(structNode => !structNode.IsHeaderDeclaration)
            .Where(structNode => structNode.TypeParameters.Count == 0)
            .ToList();

    private static string GetCFunctionName(FunctionNode function) =>
        s_nameMangler.FunctionName(function);


    private static string? GetConcreteFunctionOwnerName(FunctionNode function) =>
        FunctionOwnerTypeText(function) is not { } ownerType
            ? null
            : FunctionTypeArgumentTexts(function).Count == 0
                ? ownerType
                : LowerType($"{ownerType}<{string.Join(",", FunctionTypeArgumentTexts(function))}>");

    private static string? GetGenericBaseName(string type) =>
        CTypeLowerer.GetGenericBaseName(type);

    private static bool TrySplitQualifiedMember(string text, out string ownerName, out string memberName)
    {
        var dot = text.LastIndexOf('.');
        if (dot <= 0 || dot == text.Length - 1)
        {
            ownerName = string.Empty;
            memberName = string.Empty;
            return false;
        }

        ownerName = text[..dot];
        memberName = text[(dot + 1)..];
        return true;
    }

    private static string SubstituteGenericType(string type, IReadOnlyDictionary<string, string> substitutions)
    {
        foreach (var (parameter, argument) in substitutions)
        {
            type = Regex.Replace(type, $@"\b{Regex.Escape(parameter)}\b", argument);
        }

        return type;
    }

    private static string LowerType(string type, string? selfType = null)
        => s_abiNames.LowerType(type, selfType);

    private static string ResolveAdapterStorageType(string type)
        => CTypeLowerer.ResolveAdapterStorageType(type, s_typeAdapters);


    private static string? ResolveSelfType(FunctionNode function)
    {
        if (FunctionOwnerTypeText(function) is not { } ownerType)
        {
            return null;
        }

        var typeArguments = FunctionTypeArgumentTexts(function);
        if (typeArguments.Count > 0)
        {
            return ResolveAdapterStorageType($"{ownerType}<{string.Join(",", typeArguments)}>");
        }

        if (function.TypeParameters.Count > 0 && !TryParseGenericUse(ownerType, out _, out _))
        {
            return ResolveAdapterStorageType($"{ownerType}<{string.Join(",", function.TypeParameters)}>");
        }

        var selfParameter = function.Parameters.FirstOrDefault(parameter => parameter.Name == "self");
        if (selfParameter is not null && !Regex.IsMatch(selfParameter.TypeNode.ToTypeName(), @"\bSelf\b"))
        {
            return NormalizeType(selfParameter.TypeNode.ToTypeName());
        }

        return ResolveAdapterStorageType(ownerType);
    }

    private static string? ResolveSelfApiType(FunctionNode function)
    {
        if (FunctionOwnerTypeText(function) is not { } ownerType)
        {
            return null;
        }

        var typeArguments = FunctionTypeArgumentTexts(function);
        if (typeArguments.Count > 0)
        {
            return $"{ownerType}<{string.Join(",", typeArguments)}>";
        }

        return function.TypeParameters.Count > 0 && !TryParseGenericUse(ownerType, out _, out _)
            ? $"{ownerType}<{string.Join(",", function.TypeParameters)}>"
            : ownerType;
    }

    private static string NormalizeType(string type) => CTypeLowerer.NormalizeType(type);

    private static string RemovePointer(string type) => CTypeLowerer.RemovePointer(type);

    private static string? UnwrapPointer(string type)
    {
        type = type.Trim();
        return type.EndsWith("*", StringComparison.Ordinal)
            ? type[..^1].TrimEnd()
            : null;
    }

    private static bool TryParseGenericUse(string type, out string name, out IReadOnlyList<string> arguments)
        => CTypeLowerer.TryParseGenericUse(type, out name, out arguments);


    private static bool ReferencesCompositeType(string type, IReadOnlySet<string> compositeTypeNames)
        => CTypeLowerer.ReferencesCompositeType(type, compositeTypeNames, s_typeAdapters);

    private sealed record ResolvedAdapterExpose(
        string BaseType,
        string BaseOwner,
        string SourceName,
        IReadOnlyList<string> TypeArguments);

    private sealed record AdapterExposeInfo(
        string AdapterName,
        IReadOnlyList<string> TypeParameters,
        string BaseType,
        bool IsStatic,
        string SourceName,
        string ExposedName,
        string? ReturnType);

    private sealed record GenericCallInfo(
        string? OwnerType,
        string Name,
        IReadOnlyList<string> TypeArguments,
        IReadOnlyList<string> ParameterTypes,
        string ReturnType,
        string CName,
        bool TakesPointerSelf,
        bool IsStatic);

}
