using Cx.Compiler.C;
using Cx.Compiler.Semantic;
using Cx.Compiler.Syntax.Nodes;

namespace Cx.Compiler;

public sealed partial class CEmitter
{
    internal CTranslationUnit LowerToC(ProgramNode program)
    {
        var typeRefParser = new TypeRefParser(program);
        var backend = CBackendContext.Create(program.TypeAdapters, _nameManglerOptions, typeRefParser);
        var items = new List<CTranslationUnitItem>
        {
            new CComment("generated by Cx.Compiler"),
            new CBlankLine(),
        };

        var functionsToEmit = GetFunctionsToEmit(program);
        var emitProgram = program with { Functions = functionsToEmit };
        var includes = program.Includes
            .Concat(GetCDeclarationsToInclude(emitProgram)
                .Select(declaration => new IncludeNode(declaration.Location, declaration.HeaderPath, declaration.IsSystemHeader)))
            .DistinctBy(include => (include.Path, include.IsSystem))
            .ToList();
        var usesNull = CNullUsageAnalyzer.UsesNull(emitProgram);
        if (usesNull && !includes.Any(include => include.IsSystem && include.Path == "stddef.h"))
        {
            items.Add(new CInclude("stddef.h", IsSystem: true));
        }

        foreach (var include in includes)
        {
            items.Add(new CInclude(include.Path, include.IsSystem));
        }

        if (includes.Count > 0 || usesNull)
        {
            items.Add(new CBlankLine());
        }

        foreach (var externFunction in program.ExternFunctions.Where(function => !function.IsHeaderDeclaration))
        {
            items.Add(ToCFunctionDeclaration(backend, externFunction));
        }

        if (program.ExternFunctions.Any(function => !function.IsHeaderDeclaration))
        {
            items.Add(new CBlankLine());
        }

        var structsToEmit = GetStructsToEmit(emitProgram);
        var compositeTypeNames = structsToEmit
            .Select(structNode => structNode.Name)
            .Concat(emitProgram.TaggedUnions.Where(union => !union.IsHeaderDeclaration).Select(taggedUnion => taggedUnion.Name))
            .ToHashSet(StringComparer.Ordinal);
        var emittedTypeAliases = program.TypeAliases
            .Where(typeAlias => !typeAlias.IsHeaderDeclaration)
            .ToList();
        var earlyTypeAliases = emittedTypeAliases
            .Where(typeAlias => !ReferencesCompositeType(backend, TypeAliasTargetTypeText(typeAlias), compositeTypeNames))
            .ToList();
        var lateTypeAliases = emittedTypeAliases
            .Where(typeAlias => ReferencesCompositeType(backend, TypeAliasTargetTypeText(typeAlias), compositeTypeNames))
            .ToList();

        foreach (var typeAlias in earlyTypeAliases)
        {
            items.Add(ToCTypeAlias(backend, typeAlias));
        }

        if (earlyTypeAliases.Count > 0)
        {
            items.Add(new CBlankLine());
        }

        foreach (var enumNode in emitProgram.Enums.Where(enumNode => !enumNode.IsHeaderDeclaration))
        {
            items.Add(ToCEnum(enumNode));
            items.Add(new CBlankLine());
        }

        var interfaceImplementations = CInterfaceImplementationCollector.Collect(emitProgram, structsToEmit);
        if (emitProgram.Interfaces.Count > 0)
        {
            items.Add(ToCTypeIdEnum(backend, interfaceImplementations));
            items.Add(new CBlankLine());
        }

        foreach (var interfaceNode in emitProgram.Interfaces)
        {
            items.Add(ToCInterfaceVTableStruct(backend, interfaceNode));
            items.Add(new CBlankLine());
            items.Add(ToCInterfaceValueStruct(backend, interfaceNode));
            items.Add(new CBlankLine());
        }

        var taggedUnionNames = emitProgram.TaggedUnions
            .Where(union => !union.IsRaw)
            .Select(taggedUnion => taggedUnion.Name)
            .ToHashSet(StringComparer.Ordinal);
        var lateStructNames = structsToEmit
            .Where(structNode => structNode.Fields.Any(field => ReferencesCompositeType(backend, StructFieldTypeText(field), taggedUnionNames)))
            .Select(structNode => structNode.Name)
            .ToHashSet(StringComparer.Ordinal);
        var changed = true;
        while (changed)
        {
            changed = false;
            foreach (var structNode in structsToEmit)
            {
                if (lateStructNames.Contains(structNode.Name)
                    || !structNode.Fields.Any(field => ReferencesCompositeType(backend, StructFieldTypeText(field), lateStructNames)))
                {
                    continue;
                }

                lateStructNames.Add(structNode.Name);
                changed = true;
            }
        }

        var earlyStructs = OrderStructsByFieldDependencies(
            backend,
            structsToEmit.Where(structNode => !lateStructNames.Contains(structNode.Name)).ToList());
        var lateStructs = OrderStructsByFieldDependencies(
            backend,
            structsToEmit.Where(structNode => lateStructNames.Contains(structNode.Name)).ToList());

        foreach (var structNode in earlyStructs)
        {
            items.Add(ToCStruct(backend, structNode));
            items.Add(new CBlankLine());
        }

        foreach (var taggedUnion in emitProgram.TaggedUnions.Where(union => !union.IsHeaderDeclaration))
        {
            items.Add(ToCTaggedUnion(backend, taggedUnion));
            items.Add(new CBlankLine());
        }

        foreach (var structNode in lateStructs)
        {
            items.Add(ToCStruct(backend, structNode));
            items.Add(new CBlankLine());
        }

        foreach (var typeAlias in lateTypeAliases)
        {
            items.Add(ToCTypeAlias(backend, typeAlias));
        }

        if (lateTypeAliases.Count > 0)
        {
            items.Add(new CBlankLine());
        }

        var nameLowerer = new ImportedNameLowerer(emitProgram, structsToEmit, backend);

        foreach (var implementation in interfaceImplementations)
        {
            items.Add(ToCInterfaceVTableDeclaration(backend, implementation));
        }

        if (interfaceImplementations.Count > 0)
        {
            items.Add(new CBlankLine());
        }

        foreach (var global in emitProgram.GlobalVariables.Where(global => !global.IsHeaderDeclaration))
        {
            items.Add(ToCGlobalDeclaration(backend, global, nameLowerer));
        }

        if (emitProgram.GlobalVariables.Any(global => !global.IsHeaderDeclaration))
        {
            items.Add(new CBlankLine());
        }

        foreach (var function in functionsToEmit)
        {
            items.Add(ToCFunctionDeclaration(backend, function));
        }

        if (program.Functions.Count > 0)
        {
            items.Add(new CBlankLine());
        }

        foreach (var implementation in interfaceImplementations)
        {
            items.Add(ToCInterfaceVTableInstance(backend, implementation, functionsToEmit));
            items.Add(new CBlankLine());
        }

        foreach (var function in functionsToEmit)
        {
            items.Add(ToCFunctionDefinition(function, nameLowerer.ForFunction(function)));
            items.Add(new CBlankLine());
        }

        return new CTranslationUnit(items);
    }
}
