using System.Text;
using System.Text.RegularExpressions;
using Cx.Compiler.C;
using Cx.Compiler.Lowering;
using Cx.Compiler.Semantic;
using Cx.Compiler.Syntax.Nodes;

namespace Cx.Compiler;

public sealed partial class CEmitter
{
    private static IReadOnlyList<TypeAdapterNode> s_typeAdapters = [];
    private static CAbiNameService s_abiNames = new(s_typeAdapters);
    private static CNameMangler s_nameMangler = CreateNameMangler();

    public CEmitter()
        : this(null)
    {
    }

    internal CEmitter(CNameManglerOptions? nameManglerOptions)
    {
        s_nameMangler = CreateNameMangler(nameManglerOptions);
    }

    public string Emit(ProgramNode program) =>
        Emit(LowerToC(program));

    internal string Emit(CTranslationUnit unit) =>
        new CTranslationUnitEmitter().Emit(unit);

    internal CTranslationUnit LowerToC(ProgramNode program)
    {
        s_typeAdapters = program.TypeAdapters;
        s_abiNames = new CAbiNameService(s_typeAdapters);
        s_nameMangler = CreateNameMangler(s_nameMangler.Options);
        var items = new List<CTranslationUnitItem>
        {
            new CComment("generated by Cx.Compiler"),
            new CBlankLine(),
        };

        var functionsToEmit = GetFunctionsToEmit(program);
        var emitProgram = program with { Functions = functionsToEmit };
        var includes = program.Includes
            .Concat(GetCDeclarationsToInclude(emitProgram)
                .Select(declaration => new IncludeNode(declaration.Location, declaration.HeaderPath, declaration.IsSystemHeader)))
            .DistinctBy(include => (include.Path, include.IsSystem))
            .ToList();
        if (UsesNull(emitProgram) && !includes.Any(include => include.IsSystem && include.Path == "stddef.h"))
        {
            items.Add(new CInclude("stddef.h", IsSystem: true));
        }

        foreach (var include in includes)
        {
            items.Add(new CInclude(include.Path, include.IsSystem));
        }

        if (includes.Count > 0 || UsesNull(emitProgram))
        {
            items.Add(new CBlankLine());
        }

        foreach (var externFunction in program.ExternFunctions.Where(function => !function.IsHeaderDeclaration))
        {
            items.Add(ToCFunctionDeclaration(externFunction));
        }

        if (program.ExternFunctions.Any(function => !function.IsHeaderDeclaration))
        {
            items.Add(new CBlankLine());
        }

        var structsToEmit = GetStructsToEmit(emitProgram);
        var compositeTypeNames = structsToEmit
            .Select(structNode => structNode.Name)
            .Concat(emitProgram.TaggedUnions.Where(union => !union.IsHeaderDeclaration).Select(taggedUnion => taggedUnion.Name))
            .ToHashSet(StringComparer.Ordinal);
        var emittedTypeAliases = program.TypeAliases
            .Where(typeAlias => !typeAlias.IsHeaderDeclaration)
            .ToList();
        var earlyTypeAliases = emittedTypeAliases
            .Where(typeAlias => !ReferencesCompositeType(TypeAliasTargetTypeText(typeAlias), compositeTypeNames))
            .ToList();
        var lateTypeAliases = emittedTypeAliases
            .Where(typeAlias => ReferencesCompositeType(TypeAliasTargetTypeText(typeAlias), compositeTypeNames))
            .ToList();

        foreach (var typeAlias in earlyTypeAliases)
        {
            items.Add(ToCTypeAlias(typeAlias));
        }

        if (earlyTypeAliases.Count > 0)
        {
            items.Add(new CBlankLine());
        }

        foreach (var enumNode in emitProgram.Enums.Where(enumNode => !enumNode.IsHeaderDeclaration))
        {
            items.Add(ToCEnum(enumNode));
            items.Add(new CBlankLine());
        }

        var interfaceImplementations = GetInterfaceImplementations(emitProgram, structsToEmit);
        if (emitProgram.Interfaces.Count > 0)
        {
            items.Add(ToCTypeIdEnum(interfaceImplementations));
            items.Add(new CBlankLine());
        }

        foreach (var interfaceNode in emitProgram.Interfaces)
        {
            items.Add(ToCInterfaceVTableStruct(interfaceNode));
            items.Add(new CBlankLine());
            items.Add(ToCInterfaceValueStruct(interfaceNode));
            items.Add(new CBlankLine());
        }

        var taggedUnionNames = emitProgram.TaggedUnions
            .Where(union => !union.IsRaw)
            .Select(taggedUnion => taggedUnion.Name)
            .ToHashSet(StringComparer.Ordinal);
        var lateStructNames = structsToEmit
            .Where(structNode => structNode.Fields.Any(field => ReferencesCompositeType(StructFieldTypeText(field), taggedUnionNames)))
            .Select(structNode => structNode.Name)
            .ToHashSet(StringComparer.Ordinal);
        var changed = true;
        while (changed)
        {
            changed = false;
            foreach (var structNode in structsToEmit)
            {
                if (lateStructNames.Contains(structNode.Name)
                    || !structNode.Fields.Any(field => ReferencesCompositeType(StructFieldTypeText(field), lateStructNames)))
                {
                    continue;
                }

                lateStructNames.Add(structNode.Name);
                changed = true;
            }
        }

        var earlyStructs = OrderStructsByFieldDependencies(
            structsToEmit.Where(structNode => !lateStructNames.Contains(structNode.Name)).ToList());
        var lateStructs = OrderStructsByFieldDependencies(
            structsToEmit.Where(structNode => lateStructNames.Contains(structNode.Name)).ToList());

        foreach (var structNode in earlyStructs)
        {
            items.Add(ToCStruct(structNode));
            items.Add(new CBlankLine());
        }

        foreach (var taggedUnion in emitProgram.TaggedUnions.Where(union => !union.IsHeaderDeclaration))
        {
            items.Add(ToCTaggedUnion(taggedUnion));
            items.Add(new CBlankLine());
        }

        foreach (var structNode in lateStructs)
        {
            items.Add(ToCStruct(structNode));
            items.Add(new CBlankLine());
        }

        foreach (var typeAlias in lateTypeAliases)
        {
            items.Add(ToCTypeAlias(typeAlias));
        }

        if (lateTypeAliases.Count > 0)
        {
            items.Add(new CBlankLine());
        }

        var nameLowerer = new ImportedNameLowerer(emitProgram, structsToEmit);

        foreach (var implementation in interfaceImplementations)
        {
            items.Add(ToCInterfaceVTableDeclaration(implementation));
        }

        if (interfaceImplementations.Count > 0)
        {
            items.Add(new CBlankLine());
        }

        foreach (var global in emitProgram.GlobalVariables.Where(global => !global.IsHeaderDeclaration))
        {
            items.Add(ToCGlobalDeclaration(global, nameLowerer));
        }

        if (emitProgram.GlobalVariables.Any(global => !global.IsHeaderDeclaration))
        {
            items.Add(new CBlankLine());
        }

        foreach (var function in functionsToEmit)
        {
            items.Add(ToCFunctionDeclaration(function));
        }

        if (program.Functions.Count > 0)
        {
            items.Add(new CBlankLine());
        }

        foreach (var implementation in interfaceImplementations)
        {
            items.Add(ToCInterfaceVTableInstance(implementation, functionsToEmit));
            items.Add(new CBlankLine());
        }

        foreach (var function in functionsToEmit)
        {
            items.Add(ToCFunctionDefinition(function, nameLowerer.ForFunction(function)));
            items.Add(new CBlankLine());
        }

        return new CTranslationUnit(items);
    }

    private static CNameMangler CreateNameMangler(CNameManglerOptions? options = null) =>
        new(
            type => s_abiNames.LowerType(type),
            s_abiNames.SanitizeTypeName,
            options);

    private static void AddRaw(ICollection<CTranslationUnitItem> items, Action<StringBuilder> render)
    {
        var builder = new StringBuilder();
        render(builder);
        if (builder.Length > 0)
        {
            items.Add(new CRawTopLevel(builder.ToString()));
        }
    }

    private static CEnumDeclaration ToCEnum(EnumNode enumNode) =>
        new(
            enumNode.Name,
            enumNode.Members
                .Select(member => new CEnumMember(member.Name, member.Value))
                .ToList());

    private static CStructDeclaration ToCStruct(StructNode structNode) =>
        new(
            structNode.Name,
            structNode.Fields
                .Select(field => LowerStructFieldDeclaration(structNode, field))
                .ToList());

    private static CEnumDeclaration ToCTypeIdEnum(IReadOnlyList<InterfaceImplementation> implementations) =>
        new(
            "CxTypeId",
            new[] { new CEnumMember("CX_TYPE_UNKNOWN", "0") }
                .Concat(implementations
                .Select(implementation => implementation.Struct.Name)
                .Distinct(StringComparer.Ordinal)
                .Order(StringComparer.Ordinal)
                .Select(name => new CEnumMember(GetTypeIdName(name), null)))
                .ToList());

    private static CStructDeclaration ToCInterfaceVTableStruct(InterfaceNode interfaceNode)
    {
        var fields = new List<string> { "CxTypeId type_id" };
        foreach (var method in interfaceNode.Methods)
        {
            var parameters = new List<string> { "void* state" };
            parameters.AddRange(method.Parameters.Select(parameter => LowerParameterDeclaration(parameter)));
            fields.Add($"{LowerType(InterfaceMethodReturnTypeText(method))} (*{method.Name})({string.Join(", ", parameters)})");
        }

        return new CStructDeclaration(GetInterfaceVTableName(interfaceNode.Name), fields);
    }

    private static CStructDeclaration ToCInterfaceValueStruct(InterfaceNode interfaceNode)
    {
        var fields = new List<string>
        {
            "void* state",
            $"const {GetInterfaceVTableName(interfaceNode.Name)}* vtable",
        };
        return new CStructDeclaration(interfaceNode.Name, fields);
    }

    private static CRawTopLevel ToCInterfaceVTableInstance(
        InterfaceImplementation implementation,
        IReadOnlyList<FunctionNode> functions)
    {
        var builder = new StringBuilder();
        builder.AppendLine($"const {GetInterfaceVTableName(implementation.Interface.Name)} {GetInterfaceVTableInstanceName(implementation.Struct.Name, implementation.Interface.Name)} =");
        builder.AppendLine("{");
        builder.AppendLine($"    .type_id = {GetTypeIdName(implementation.Struct.Name)},");
        foreach (var method in implementation.Interface.Methods)
        {
            var concrete = functions.FirstOrDefault(function =>
                GetConcreteFunctionOwnerName(function) == implementation.Struct.Name
                && !function.IsStatic
                && function.Name == method.Name);
            if (concrete is null)
            {
                continue;
            }

            var parameters = new List<string> { "void*" };
            parameters.AddRange(method.Parameters.Select(parameter => LowerType(ParameterTypeText(parameter))));
            var slotType = $"{LowerType(InterfaceMethodReturnTypeText(method))} (*)({string.Join(", ", parameters)})";
            builder.AppendLine($"    .{method.Name} = ({slotType}){GetCFunctionName(concrete)},");
        }

        builder.AppendLine("};");
        return new CRawTopLevel(builder.ToString());
    }

    private static CRawTopLevel ToCInterfaceVTableDeclaration(InterfaceImplementation implementation) =>
        new($"extern const {GetInterfaceVTableName(implementation.Interface.Name)} {GetInterfaceVTableInstanceName(implementation.Struct.Name, implementation.Interface.Name)};{Environment.NewLine}");

    private static CTaggedUnionDeclaration ToCTaggedUnion(TaggedUnionNode taggedUnion) =>
        new(
            taggedUnion.Name,
            taggedUnion.IsRaw,
            taggedUnion.Variants
                .Select(variant => new CTaggedUnionVariantDeclaration(
                    variant.Name,
                    LowerType(variant.TypeNode, TaggedUnionVariantTypeText(variant)),
                    LowerDeclaration(variant.TypeNode, TaggedUnionVariantTypeText(variant), variant.Name)))
                .ToList());

    private static IReadOnlyList<InterfaceImplementation> GetInterfaceImplementations(
        ProgramNode program,
        IReadOnlyList<StructNode> structs)
    {
        var interfaces = program.Interfaces.ToDictionary(interfaceNode => interfaceNode.Name, StringComparer.Ordinal);
        return structs
            .Where(structNode => !structNode.IsHeaderDeclaration)
            .SelectMany(structNode => structNode.Requirements
                .Select(requirement => interfaces.TryGetValue(requirement.Name, out var interfaceNode)
                    ? new InterfaceImplementation(structNode, interfaceNode)
                    : null)
                .Where(implementation => implementation is not null)
                .Cast<InterfaceImplementation>())
            .GroupBy(implementation => (implementation.Struct.Name, implementation.Interface.Name))
            .Select(group => group.First())
            .ToList();
    }

    private static string GetInterfaceVTableName(string interfaceName) =>
        s_abiNames.InterfaceVTableName(interfaceName);

    private static string GetInterfaceVTableInstanceName(string structName, string interfaceName) =>
        s_abiNames.InterfaceVTableInstanceName(structName, interfaceName);

    private static string GetTypeIdName(string typeName) =>
        s_abiNames.TypeIdName(typeName);

    private static CTypeAliasDeclaration ToCTypeAlias(TypeAliasNode typeAlias)
    {
        var targetType = TypeAliasTargetTypeText(typeAlias);
        if (TryParseFunctionType(targetType, out var parameters, out var returnType))
        {
            return new CTypeAliasDeclaration(
                typeAlias.Name,
                LowerType(returnType),
                parameters.Select(parameter => LowerFunctionTypeParameter(parameter)).ToList());
        }

        return new CTypeAliasDeclaration(
            typeAlias.Name,
            LowerType(typeAlias.TargetTypeNode, targetType));
    }

    private static CFunctionDeclaration ToCFunctionDeclaration(FunctionNode function)
    {
        var selfType = ResolveSelfType(function);
        return new CFunctionDeclaration(
            LowerType(function.ReturnTypeNode, FunctionReturnTypeText(function), selfType),
            GetCFunctionName(function),
            function.Parameters
                .Select(parameter => LowerParameterDeclaration(parameter, selfType))
                .ToList());
    }

    private static CFunctionDefinition ToCFunctionDefinition(
        FunctionNode function,
        ImportedNameLowerer nameLowerer)
    {
        var declaration = ToCFunctionDeclaration(function);
        var statementLowerer = new CStatementLoweringPipeline(nameLowerer);
        return new CFunctionDefinition(
            declaration.ReturnType,
            declaration.Name,
            declaration.ParameterDeclarations,
            statementLowerer.LowerBlock(function.Body));
    }

    private static CFunctionDeclaration ToCFunctionDeclaration(ExternFunctionNode function) =>
        new(
            LowerType(function.ReturnTypeNode, ExternFunctionReturnTypeText(function)),
            function.Name,
            function.Parameters
                .Select(parameter => LowerParameterDeclaration(parameter))
                .ToList());

    private static CGlobalDeclaration ToCGlobalDeclaration(
        GlobalVariableNode global,
        ImportedNameLowerer nameLowerer)
    {
        var globalType = GlobalVariableTypeText(global);
        var declaration = (global.IsConst ? "const " : "") + LowerDeclaration(global.TypeNode, globalType, global.Name);
        var initializer = global.Initializer is null
            ? null
            : nameLowerer.LowerInitializerExpression(global.TypeNode, globalType, global.Initializer);
        return new CGlobalDeclaration(declaration, initializer);
    }

    private static IEnumerable<CDeclareNode> GetCDeclarationsToInclude(ProgramNode program)
    {
        var usage = GetCDeclarationUsage(program);
        foreach (var declaration in program.CDeclarations)
        {
            if (IsCDeclarationUsed(declaration, usage))
            {
                yield return declaration;
            }
        }
    }

    private sealed record CDeclarationUsage(
        IReadOnlySet<string> Functions,
        IReadOnlySet<string> Types,
        IReadOnlySet<string> Values);

    private static CDeclarationUsage GetCDeclarationUsage(ProgramNode program)
    {
        var declaredFunctions = program.CDeclarations
            .SelectMany(declaration => declaration.Functions)
            .Select(function => function.Name)
            .Where(name => !string.IsNullOrWhiteSpace(name))
            .ToHashSet(StringComparer.Ordinal);
        var declaredTypes = program.CDeclarations
            .SelectMany(GetCDeclarationTypeNames)
            .Where(name => !string.IsNullOrWhiteSpace(name))
            .ToHashSet(StringComparer.Ordinal);
        var declaredValues = program.CDeclarations
            .SelectMany(GetCDeclarationValueNames)
            .Where(name => !string.IsNullOrWhiteSpace(name))
            .ToHashSet(StringComparer.Ordinal);

        var functions = EnumerateExpressionNodes(program)
            .Select(GetCalledFunctionName)
            .Where(name => name is not null && declaredFunctions.Contains(name))
            .Select(name => name!)
            .ToHashSet(StringComparer.Ordinal);
        var types = EnumerateTypeReferences(program)
            .SelectMany(ExtractTypeNames)
            .Where(declaredTypes.Contains)
            .ToHashSet(StringComparer.Ordinal);
        var values = EnumerateExpressionNodes(program)
            .Select(GetValueReferenceName)
            .Where(name => name is not null && declaredValues.Contains(name))
            .Select(name => name!)
            .ToHashSet(StringComparer.Ordinal);

        return new CDeclarationUsage(functions, types, values);
    }

    private static string? GetCalledFunctionName(ExpressionNode expression) => expression switch
    {
        CallExpressionNode call => ExpressionNameFacts.GetQualifiedName(call.Callee),
        GenericCallExpressionNode call => ExpressionNameFacts.GetQualifiedName(call.Callee),
        _ => null,
    };

    private static string? GetValueReferenceName(ExpressionNode expression) => expression switch
    {
        NameExpressionNode name => name.SourceText,
        MemberExpressionNode member => ExpressionNameFacts.GetQualifiedName(member),
        _ => null,
    };

    private static IEnumerable<string> GetCDeclarationTypeNames(CDeclareNode declaration) =>
        declaration.TypeAliases.Select(typeAlias => typeAlias.Name)
            .Concat(declaration.Structs.Select(structNode => structNode.Name))
            .Concat(declaration.Enums.Select(enumNode => enumNode.Name))
            .Concat(declaration.Unions.Select(union => union.Name));

    private static IEnumerable<string> GetCDeclarationValueNames(CDeclareNode declaration) =>
        declaration.Constants.Select(constant => constant.Name)
            .Concat(declaration.Enums.SelectMany(enumNode => enumNode.Members.Select(member => member.Name)));

    private static IEnumerable<ExpressionNode> EnumerateExpressionNodes(ProgramNode program)
    {
        foreach (var global in program.GlobalVariables.Where(global => !global.IsHeaderDeclaration))
        {
            if (global.Initializer is null)
            {
                continue;
            }

            foreach (var expression in EnumerateExpressionNodes(global.Initializer))
            {
                yield return expression;
            }
        }

        foreach (var function in program.Functions)
        {
            foreach (var expression in EnumerateExpressionNodes(function.Body))
            {
                yield return expression;
            }
        }
    }

    private static IEnumerable<string> EnumerateTypeReferences(ProgramNode program)
    {
        foreach (var global in program.GlobalVariables.Where(global => !global.IsHeaderDeclaration))
        {
            yield return GlobalVariableTypeText(global);
            foreach (var type in EnumerateExpressionTypeReferences(global.Initializer))
            {
                yield return type;
            }
        }

        foreach (var typeAlias in program.TypeAliases.Where(typeAlias => !typeAlias.IsHeaderDeclaration))
        {
            yield return TypeAliasTargetTypeText(typeAlias);
        }

        foreach (var function in program.Functions)
        {
            yield return FunctionReturnTypeText(function);
            foreach (var parameter in function.Parameters.Where(parameter => !parameter.IsVariadic))
            {
                yield return ParameterTypeText(parameter);
            }

            foreach (var type in EnumerateStatementTypeReferences(function.Body))
            {
                yield return type;
            }
        }

        foreach (var structNode in program.Structs.Where(structNode => !structNode.IsHeaderDeclaration))
        {
            foreach (var field in structNode.Fields)
            {
                yield return StructFieldTypeText(field);
            }
        }

        foreach (var taggedUnion in program.TaggedUnions.Where(taggedUnion => !taggedUnion.IsHeaderDeclaration))
        {
            foreach (var variant in taggedUnion.Variants)
            {
                yield return TaggedUnionVariantTypeText(variant);
            }
        }
    }

    private static IEnumerable<string> EnumerateStatementTypeReferences(IEnumerable<StatementNode> statements)
    {
        foreach (var statement in statements)
        {
            switch (statement)
            {
                case LetStatement letStatement:
                    yield return LetStatementTypeText(letStatement);
                    foreach (var type in EnumerateExpressionTypeReferences(letStatement.Initializer))
                    {
                        yield return type;
                    }
                    break;
                case ReturnStatement returnStatement:
                    foreach (var type in EnumerateExpressionTypeReferences(returnStatement.Expression))
                    {
                        yield return type;
                    }
                    break;
                case CStatement cStatement:
                    foreach (var type in EnumerateExpressionTypeReferences(cStatement.Expression))
                    {
                        yield return type;
                    }
                    break;
                case IfStatement ifStatement:
                    foreach (var type in EnumerateExpressionTypeReferences(ifStatement.Condition)
                        .Concat(EnumerateStatementTypeReferences(ifStatement.ThenBody)))
                    {
                        yield return type;
                    }
                    if (ifStatement.ElseBranch is not null)
                    {
                        foreach (var type in EnumerateStatementTypeReferences([ifStatement.ElseBranch]))
                        {
                            yield return type;
                        }
                    }
                    break;
                case ElseBlockStatement elseBlock:
                    foreach (var type in EnumerateStatementTypeReferences(elseBlock.Body))
                    {
                        yield return type;
                    }
                    break;
                case WhileStatement whileStatement:
                    foreach (var type in EnumerateExpressionTypeReferences(whileStatement.Condition)
                        .Concat(EnumerateStatementTypeReferences(whileStatement.Body)))
                    {
                        yield return type;
                    }
                    break;
                case ForStatement forStatement:
                    foreach (var type in EnumerateForInitializerTypeReferences(forStatement.CachedRangeEndInitializer)
                        .Concat(EnumerateForInitializerTypeReferences(forStatement.CounterInitializer))
                        .Concat(EnumerateForInitializerTypeReferences(forStatement.Initializer))
                        .Concat(EnumerateExpressionTypeReferences(forStatement.Condition))
                        .Concat(EnumerateExpressionTypeReferences(forStatement.Increment))
                        .Concat(EnumerateExpressionTypeReferences(forStatement.CounterIncrement))
                        .Concat(EnumerateStatementTypeReferences(forStatement.Body)))
                    {
                        yield return type;
                    }
                    break;
                case SwitchStatement switchStatement:
                    foreach (var type in EnumerateExpressionTypeReferences(switchStatement.Expression))
                    {
                        yield return type;
                    }
                    foreach (var switchCase in switchStatement.Cases)
                    {
                        foreach (var type in EnumerateExpressionTypeReferences(switchCase.Pattern)
                            .Concat(EnumerateStatementTypeReferences(switchCase.Body)))
                        {
                            yield return type;
                        }
                    }
                    foreach (var type in EnumerateStatementTypeReferences(switchStatement.DefaultBody))
                    {
                        yield return type;
                    }
                    break;
            }
        }
    }

    private static IEnumerable<string> EnumerateForInitializerTypeReferences(ForInitializerNode? initializer) => initializer switch
    {
        ForDeclarationInitializerNode declaration => [ForDeclarationInitializerTypeText(declaration), .. EnumerateExpressionTypeReferences(declaration.Initializer)],
        ForExpressionInitializerNode expression => EnumerateExpressionTypeReferences(expression.Expression),
        _ => [],
    };

    private static IEnumerable<string> EnumerateExpressionTypeReferences(ExpressionNode? expression)
    {
        if (expression is null)
        {
            yield break;
        }

        foreach (var node in EnumerateExpressionNodes(expression))
        {
            switch (node)
            {
                case CastExpressionNode cast:
                    yield return CastExpressionTargetTypeText(cast);
                    break;
                case InitializerExpressionNode { TypeNameNode: not null } initializer:
                    yield return InitializerExpressionTypeNameText(initializer);
                    break;
                case SizeOfExpressionNode { TypeOperandNode: not null } sizeOf:
                    yield return SizeOfExpressionTypeOperandText(sizeOf);
                    break;
            }
        }
    }

    private static IEnumerable<string> ExtractTypeNames(string type)
    {
        type = NormalizeTypeReferenceText(type);
        foreach (Match match in Regex.Matches(type, @"[A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)?"))
        {
            var name = match.Value;
            if (!IsTypeReferenceKeyword(name))
            {
                yield return name;
            }
        }
    }

    private static string NormalizeTypeReferenceText(string type) =>
        type
            .Replace("*", " ", StringComparison.Ordinal)
            .Replace("[", " ", StringComparison.Ordinal)
            .Replace("]", " ", StringComparison.Ordinal)
            .Replace("(", " ", StringComparison.Ordinal)
            .Replace(")", " ", StringComparison.Ordinal)
            .Replace(",", " ", StringComparison.Ordinal)
            .Replace("->", " ", StringComparison.Ordinal)
            .Replace("<", " ", StringComparison.Ordinal)
            .Replace(">", " ", StringComparison.Ordinal);

    private static bool IsTypeReferenceKeyword(string name) =>
        name is
            "const" or
            "fn" or
            "opaque" or
            "void" or
            "char" or
            "short" or
            "int" or
            "long" or
            "float" or
            "double" or
            "bool" or
            "usize" or
            "i8" or
            "i16" or
            "i32" or
            "i64" or
            "u8" or
            "u16" or
            "u32" or
            "u64";

    private static bool IsCDeclarationUsed(CDeclareNode declaration, CDeclarationUsage usage) =>
        declaration.Functions.Any(function => usage.Functions.Contains(function.Name))
        || GetCDeclarationTypeNames(declaration).Any(usage.Types.Contains)
        || GetCDeclarationValueNames(declaration).Any(usage.Values.Contains);

    private static void EmitStruct(StringBuilder builder, StructNode structNode)
    {
        builder.AppendLine($"typedef struct {structNode.Name}");
        builder.AppendLine("{");

        foreach (var field in structNode.Fields)
        {
            builder.AppendLine($"    {LowerStructFieldDeclaration(structNode, field)};");
        }

        builder.AppendLine($"}} {structNode.Name};");
    }

    private static string LowerStructFieldDeclaration(StructNode structNode, StructFieldNode field)
    {
        var selfPointerType = structNode.Name + "*";
        var fieldType = StructFieldTypeText(field);
        return fieldType == selfPointerType
            ? $"struct {structNode.Name}* {field.Name}"
            : LowerDeclaration(field.TypeNode, fieldType, field.Name);
    }

    private static void EmitEnum(StringBuilder builder, EnumNode enumNode)
    {
        builder.AppendLine("typedef enum");
        builder.AppendLine("{");

        for (var i = 0; i < enumNode.Members.Count; i++)
        {
            var member = enumNode.Members[i];
            var value = string.IsNullOrWhiteSpace(member.Value) ? "" : " = " + member.Value;
            var comma = i == enumNode.Members.Count - 1 ? "" : ",";
            builder.AppendLine($"    {member.Name}{value}{comma}");
        }

        builder.AppendLine($"}} {enumNode.Name};");
    }

    private static IReadOnlyList<FunctionNode> GetFunctionsToEmit(ProgramNode program)
    =>
        program.Functions
            .Where(function => function.TypeParameters.Count == 0)
            .ToList();

    private static IEnumerable<ExpressionNode> EnumerateExpressionNodes(IEnumerable<StatementNode> statements)
    {
        foreach (var statement in statements)
        {
            switch (statement)
            {
                case LetStatement { Initializer: not null } let:
                    foreach (var expression in EnumerateExpressionNodes(let.Initializer))
                    {
                        yield return expression;
                    }
                    break;
                case ReturnStatement { Expression: not null } ret:
                    foreach (var expression in EnumerateExpressionNodes(ret.Expression))
                    {
                        yield return expression;
                    }
                    break;
                case CStatement c:
                    foreach (var expression in EnumerateExpressionNodes(c.Expression))
                    {
                        yield return expression;
                    }
                    break;
                case IfStatement ifStatement:
                    foreach (var expression in EnumerateExpressionNodes(ifStatement.Condition))
                    {
                        yield return expression;
                    }

                    foreach (var expression in EnumerateExpressionNodes(ifStatement.ThenBody))
                    {
                        yield return expression;
                    }

                    if (ifStatement.ElseBranch is not null)
                    {
                        foreach (var expression in EnumerateExpressionNodes([ifStatement.ElseBranch]))
                        {
                            yield return expression;
                        }
                    }
                    break;
                case ElseBlockStatement elseBlock:
                    foreach (var expression in EnumerateExpressionNodes(elseBlock.Body))
                    {
                        yield return expression;
                    }
                    break;
                case WhileStatement whileStatement:
                    foreach (var expression in EnumerateExpressionNodes(whileStatement.Condition))
                    {
                        yield return expression;
                    }

                    foreach (var expression in EnumerateExpressionNodes(whileStatement.Body))
                    {
                        yield return expression;
                    }
                    break;
                case ForStatement forStatement:
                    if (forStatement.CachedRangeEndInitializer is { Initializer: not null } cachedRangeEnd)
                    {
                        foreach (var expression in EnumerateExpressionNodes(cachedRangeEnd.Initializer))
                        {
                            yield return expression;
                        }
                    }

                    if (forStatement.CounterInitializer is { Initializer: not null } counter)
                    {
                        foreach (var expression in EnumerateExpressionNodes(counter.Initializer))
                        {
                            yield return expression;
                        }
                    }

                    if (forStatement.Initializer is ForDeclarationInitializerNode { Initializer: not null } declaration)
                    {
                        foreach (var expression in EnumerateExpressionNodes(declaration.Initializer))
                        {
                            yield return expression;
                        }
                    }
                    else if (forStatement.Initializer is ForExpressionInitializerNode initializer)
                    {
                        foreach (var expression in EnumerateExpressionNodes(initializer.Expression))
                        {
                            yield return expression;
                        }
                    }

                    foreach (var expression in EnumerateExpressionNodes(forStatement.Condition))
                    {
                        yield return expression;
                    }

                    foreach (var expression in EnumerateExpressionNodes(forStatement.Increment))
                    {
                        yield return expression;
                    }

                    if (forStatement.CounterIncrement is not null)
                    {
                        foreach (var expression in EnumerateExpressionNodes(forStatement.CounterIncrement))
                        {
                            yield return expression;
                        }
                    }

                    foreach (var expression in EnumerateExpressionNodes(forStatement.Body))
                    {
                        yield return expression;
                    }
                    break;
                case SwitchStatement switchStatement:
                    foreach (var expression in EnumerateExpressionNodes(switchStatement.Expression))
                    {
                        yield return expression;
                    }

                    foreach (var switchCase in switchStatement.Cases)
                    {
                        foreach (var expression in EnumerateExpressionNodes(switchCase.Pattern))
                        {
                            yield return expression;
                        }

                        foreach (var expression in EnumerateExpressionNodes(switchCase.Body))
                        {
                            yield return expression;
                        }
                    }

                    foreach (var expression in EnumerateExpressionNodes(switchStatement.DefaultBody))
                    {
                        yield return expression;
                    }
                    break;
            }
        }
    }

    private static IEnumerable<ExpressionNode> EnumerateExpressionNodes(ExpressionNode expression)
    {
        yield return expression;
        switch (expression)
        {
            case ParenthesizedExpressionNode parenthesized:
                foreach (var child in EnumerateExpressionNodes(parenthesized.Expression)) yield return child;
                break;
            case CastExpressionNode cast:
                foreach (var child in EnumerateExpressionNodes(cast.Expression)) yield return child;
                break;
            case UnaryExpressionNode unary:
                foreach (var child in EnumerateExpressionNodes(unary.Operand)) yield return child;
                break;
            case PostfixExpressionNode postfix:
                foreach (var child in EnumerateExpressionNodes(postfix.Operand)) yield return child;
                break;
            case SizeOfExpressionNode { ExpressionOperand: not null } sizeOf:
                foreach (var child in EnumerateExpressionNodes(sizeOf.ExpressionOperand)) yield return child;
                break;
            case BinaryExpressionNode binary:
                foreach (var child in EnumerateExpressionNodes(binary.Left)) yield return child;
                foreach (var child in EnumerateExpressionNodes(binary.Right)) yield return child;
                break;
            case ScalarRangeExpressionNode range:
                foreach (var child in EnumerateExpressionNodes(range.Start)) yield return child;
                foreach (var child in EnumerateExpressionNodes(range.End)) yield return child;
                break;
            case ConditionalExpressionNode conditional:
                foreach (var child in EnumerateExpressionNodes(conditional.Condition)) yield return child;
                foreach (var child in EnumerateExpressionNodes(conditional.WhenTrue)) yield return child;
                foreach (var child in EnumerateExpressionNodes(conditional.WhenFalse)) yield return child;
                break;
            case InitializerExpressionNode initializer:
                foreach (var field in initializer.Fields)
                {
                    foreach (var child in EnumerateExpressionNodes(field.Value)) yield return child;
                }

                foreach (var value in initializer.Values)
                {
                    foreach (var child in EnumerateExpressionNodes(value)) yield return child;
                }
                break;
            case FunctionExpressionNode function:
                if (function.ExpressionBody is not null)
                {
                    foreach (var child in EnumerateExpressionNodes(function.ExpressionBody)) yield return child;
                }

                if (function.BlockBody is not null)
                {
                    foreach (var child in EnumerateExpressionNodes(function.BlockBody)) yield return child;
                }
                break;
            case AssignmentExpressionNode assignment:
                foreach (var child in EnumerateExpressionNodes(assignment.Target)) yield return child;
                foreach (var child in EnumerateExpressionNodes(assignment.Value)) yield return child;
                break;
            case CallExpressionNode call:
                foreach (var child in EnumerateExpressionNodes(call.Callee)) yield return child;
                foreach (var argument in call.Arguments)
                {
                    foreach (var child in EnumerateExpressionNodes(argument)) yield return child;
                }
                break;
            case GenericCallExpressionNode call:
                foreach (var child in EnumerateExpressionNodes(call.Callee)) yield return child;
                foreach (var argument in call.Arguments)
                {
                    foreach (var child in EnumerateExpressionNodes(argument)) yield return child;
                }
                break;
            case MemberExpressionNode member:
                foreach (var child in EnumerateExpressionNodes(member.Target)) yield return child;
                break;
            case IndexExpressionNode index:
                foreach (var child in EnumerateExpressionNodes(index.Target)) yield return child;
                foreach (var child in EnumerateExpressionNodes(index.Index)) yield return child;
                break;
        }
    }

    private static IEnumerable<(string Name, string Type)> CollectLocalVariables(IEnumerable<StatementNode> statements)
    {
        foreach (var statement in statements)
        {
            switch (statement)
            {
                case LetStatement let:
                    yield return (let.Name, LetStatementTypeText(let));
                    break;
                case IfStatement ifStatement:
                    foreach (var variable in CollectLocalVariables(ifStatement.ThenBody))
                    {
                        yield return variable;
                    }

                    if (ifStatement.ElseBranch is not null)
                    {
                        foreach (var variable in CollectLocalVariables([ifStatement.ElseBranch]))
                        {
                            yield return variable;
                        }
                    }

                    break;
                case ElseBlockStatement elseBlock:
                    foreach (var variable in CollectLocalVariables(elseBlock.Body))
                    {
                        yield return variable;
                    }
                    break;
                case WhileStatement whileStatement:
                    foreach (var variable in CollectLocalVariables(whileStatement.Body))
                    {
                        yield return variable;
                    }
                    break;
                case ForStatement forStatement:
                    if (forStatement.CachedRangeEndInitializer is not null)
                    {
                        yield return (forStatement.CachedRangeEndInitializer.Name, ForDeclarationInitializerTypeText(forStatement.CachedRangeEndInitializer));
                    }

                    if (forStatement.CounterInitializer is not null)
                    {
                        yield return (forStatement.CounterInitializer.Name, ForDeclarationInitializerTypeText(forStatement.CounterInitializer));
                    }

                    if (forStatement.Initializer is ForDeclarationInitializerNode declaration)
                    {
                        yield return (declaration.Name, ForDeclarationInitializerTypeText(declaration));
                    }

                    foreach (var variable in CollectLocalVariables(forStatement.Body))
                    {
                        yield return variable;
                    }
                    break;
                case SwitchStatement switchStatement:
                    foreach (var switchCase in switchStatement.Cases)
                    {
                        foreach (var variable in CollectLocalVariables(switchCase.Body))
                        {
                            yield return variable;
                        }
                    }

                    foreach (var variable in CollectLocalVariables(switchStatement.DefaultBody))
                    {
                        yield return variable;
                    }
                    break;
            }
        }
    }

    private static string SubstituteAdapterBaseType(TypeAdapterNode adapter, IReadOnlyList<string> receiverArguments)
    {
        if (adapter.TypeParameters.Count == 0 || adapter.TypeParameters.Count != receiverArguments.Count)
        {
            return TypeAdapterBaseTypeText(adapter);
        }

        var substitutions = adapter.TypeParameters
            .Zip(receiverArguments)
            .ToDictionary(pair => pair.First, pair => pair.Second, StringComparer.Ordinal);
        return SubstituteGenericType(TypeAdapterBaseTypeText(adapter), substitutions);
    }

    private static ResolvedAdapterExpose ResolveAdapterExpose(
        IReadOnlyList<TypeAdapterNode> adapters,
        TypeAdapterNode adapter,
        ExposeMethodNode expose,
        IReadOnlyList<string> receiverArguments)
    {
        var currentAdapter = adapter;
        var currentExpose = expose;
        var currentArguments = receiverArguments;
        var seen = new HashSet<string>(StringComparer.Ordinal);

        while (true)
        {
            var baseType = SubstituteAdapterBaseType(currentAdapter, currentArguments);
            var baseOwner = GetGenericBaseName(baseType) ?? baseType;
            var baseArguments = TryParseGenericUse(baseType, out _, out var parsedBaseArguments)
                ? parsedBaseArguments
                : [];
            var key = $"{currentAdapter.Name}.{currentExpose.ExposedName}";
            if (!seen.Add(key))
            {
                return new ResolvedAdapterExpose(baseType, baseOwner, currentExpose.SourceName, baseArguments);
            }

            var nextAdapter = adapters.FirstOrDefault(adapter => adapter.Name == baseOwner);
            var nextExpose = nextAdapter?.ExposedMethods.FirstOrDefault(expose =>
                expose.IsStatic == currentExpose.IsStatic
                && expose.ExposedName == currentExpose.SourceName);
            if (nextAdapter is null || nextExpose is null)
            {
                return new ResolvedAdapterExpose(baseType, baseOwner, currentExpose.SourceName, baseArguments);
            }

            currentAdapter = nextAdapter;
            currentExpose = nextExpose;
            currentArguments = baseArguments;
        }
    }

    private static IReadOnlyList<StructNode> GetStructsToEmit(ProgramNode program)
    =>
        program.Structs
            .Where(structNode => !structNode.IsHeaderDeclaration)
            .Where(structNode => structNode.TypeParameters.Count == 0)
            .ToList();

    private static bool TryParseFixedArrayType(string type, out string elementType, out string length)
        => CTypeLowerer.TryParseFixedArrayType(type, out elementType, out length);

    private static string GetCFunctionName(FunctionNode function) =>
        s_nameMangler.FunctionName(function);

    private static string GetFunctionKey(FunctionNode function) =>
        FunctionOwnerTypeText(function) is { } ownerType ? $"{ownerType}.{function.Name}" : function.Name;

    private static string? GetConcreteFunctionOwnerName(FunctionNode function) =>
        FunctionOwnerTypeText(function) is not { } ownerType
            ? null
            : FunctionTypeArgumentTexts(function).Count == 0
                ? ownerType
                : LowerType($"{ownerType}<{string.Join(",", FunctionTypeArgumentTexts(function))}>");

    private static string? GetGenericBaseName(string type) =>
        CTypeLowerer.GetGenericBaseName(type);

    private static bool TrySplitQualifiedMember(string text, out string ownerName, out string memberName)
    {
        var dot = text.LastIndexOf('.');
        if (dot <= 0 || dot == text.Length - 1)
        {
            ownerName = string.Empty;
            memberName = string.Empty;
            return false;
        }

        ownerName = text[..dot];
        memberName = text[(dot + 1)..];
        return true;
    }

    private static int FindMatchingGenericClose(string type, int openIndex)
    {
        var depth = 0;
        for (var i = openIndex; i < type.Length; i++)
        {
            if (type[i] == '<')
            {
                depth++;
                continue;
            }

            if (type[i] != '>')
            {
                continue;
            }

            depth--;
            if (depth == 0)
            {
                return i;
            }
        }

        return -1;
    }

    private static IReadOnlyList<string> SplitGenericArguments(string argumentsText)
    {
        if (string.IsNullOrWhiteSpace(argumentsText))
        {
            return [];
        }

        var arguments = new List<string>();
        var start = 0;
        var angleDepth = 0;
        var parenDepth = 0;
        var bracketDepth = 0;

        for (var i = 0; i < argumentsText.Length; i++)
        {
            switch (argumentsText[i])
            {
                case '<': angleDepth++; break;
                case '>': angleDepth--; break;
                case '(': parenDepth++; break;
                case ')': parenDepth--; break;
                case '[': bracketDepth++; break;
                case ']': bracketDepth--; break;
            }

            if (argumentsText[i] != ',' || angleDepth != 0 || parenDepth != 0 || bracketDepth != 0)
            {
                continue;
            }

            arguments.Add(argumentsText[start..i].Trim());
            start = i + 1;
        }

        arguments.Add(argumentsText[start..].Trim());
        return arguments;
    }

    private static string SubstituteGenericType(string type, IReadOnlyDictionary<string, string> substitutions)
    {
        foreach (var (parameter, argument) in substitutions)
        {
            type = Regex.Replace(type, $@"\b{Regex.Escape(parameter)}\b", argument);
        }

        return type;
    }

    private static bool IsIdentifierStart(char ch) => char.IsLetter(ch) || ch == '_';

    private static bool IsIdentifierPart(char ch) => char.IsLetterOrDigit(ch) || ch == '_';

    private static void AppendIndent(StringBuilder builder, int indentLevel) =>
        builder.Append(' ', indentLevel * 4);

    private static string IndentLine(string text, int indentLevel) =>
        new string(' ', indentLevel * 4) + text + Environment.NewLine;

    private static string LowerType(string type, string? selfType = null)
        => s_abiNames.LowerType(type, selfType);

    private static string LowerType(TypeNode? typeNode, string fallbackType, string? selfType = null) =>
        s_abiNames.LowerType(typeNode, fallbackType, selfType);

    private static string TaggedUnionVariantTypeText(TaggedUnionVariantNode variant) =>
        variant.TypeNode?.Semantic.Type is { } type
            ? TypeRefFormatter.ToCxString(type)
            : variant.TypeNode.ToTypeName();

    private static string TypeAliasTargetTypeText(TypeAliasNode typeAlias) =>
        typeAlias.TargetTypeNode?.Semantic.Type is { } type
            ? TypeRefFormatter.ToCxString(type)
            : typeAlias.TargetTypeNode.ToTypeName();

    private static string TypeAdapterBaseTypeText(TypeAdapterNode adapter) =>
        adapter.BaseTypeNode?.Semantic.Type is { } type
            ? TypeRefFormatter.ToCxString(type)
            : adapter.BaseTypeNode.ToTypeName();

    private static string? FunctionOwnerTypeText(FunctionNode function) =>
        function.OwnerTypeNode is null
            ? null
            : function.OwnerTypeNode.Semantic.Type is { } type
                ? TypeRefFormatter.ToCxString(type)
                : function.OwnerTypeNode.ToTypeName();

    private static string FunctionReturnTypeText(FunctionNode function) =>
        function.ReturnTypeNode?.Semantic.Type is { } type
            ? TypeRefFormatter.ToCxString(type)
            : function.ReturnTypeNode.ToTypeName();

    private static string ParameterTypeText(ParameterNode parameter) =>
        parameter.TypeNode?.Semantic.Type is { } type
            ? TypeRefFormatter.ToCxString(type)
            : parameter.TypeNode.ToTypeName();

    private static string GlobalVariableTypeText(GlobalVariableNode global) =>
        global.TypeNode?.Semantic.Type is { } type
            ? TypeRefFormatter.ToCxString(type)
            : global.TypeNode.ToTypeName();

    private static string ForDeclarationInitializerTypeText(ForDeclarationInitializerNode initializer) =>
        initializer.TypeNode?.Semantic.Type is { } type
            ? TypeRefFormatter.ToCxString(type)
            : initializer.TypeNode.ToTypeName();

    private static string LetStatementTypeText(LetStatement let) =>
        let.TypeNode?.Semantic.Type is { } type
            ? TypeRefFormatter.ToCxString(type)
            : let.TypeNode.ToTypeName();

    private static string CastExpressionTargetTypeText(CastExpressionNode cast) =>
        cast.TargetTypeNode?.Semantic.Type is { } type
            ? TypeRefFormatter.ToCxString(type)
            : cast.TargetTypeNode.ToTypeName();

    private static string SizeOfExpressionTypeOperandText(SizeOfExpressionNode sizeOf) =>
        sizeOf.TypeOperandNode?.Semantic.Type is { } type
            ? TypeRefFormatter.ToCxString(type)
            : sizeOf.TypeOperandNode.ToTypeName();

    private static string InitializerExpressionTypeNameText(InitializerExpressionNode initializer) =>
        initializer.TypeNameNode?.Semantic.Type is { } type
            ? TypeRefFormatter.ToCxString(type)
            : initializer.TypeNameNode.ToTypeName();

    private static string InterfaceMethodReturnTypeText(InterfaceMethodNode method) =>
        method.ReturnTypeNode?.Semantic.Type is { } type
            ? TypeRefFormatter.ToCxString(type)
            : method.ReturnTypeNode.ToTypeName();

    private static string ExternFunctionReturnTypeText(ExternFunctionNode function) =>
        function.ReturnTypeNode?.Semantic.Type is { } type
            ? TypeRefFormatter.ToCxString(type)
            : function.ReturnTypeNode.ToTypeName();

    private static IReadOnlyList<string> FunctionTypeArgumentTexts(FunctionNode function) =>
        (function.TypeArgumentNodes ?? [])
            .Select(typeArgument => typeArgument.Semantic.Type is { } type
                ? TypeRefFormatter.ToCxString(type)
                : typeArgument.ToTypeName())
            .ToList();

    private static string StructFieldTypeText(StructFieldNode field) =>
        field.TypeNode?.Semantic.Type is { } type
            ? TypeRefFormatter.ToCxString(type)
            : field.TypeNode.ToTypeName();

    private static string ResolveAdapterStorageType(string type)
        => CTypeLowerer.ResolveAdapterStorageType(type, s_typeAdapters);

    private static string StripModuleQualifier(string type)
    {
        var prefix = "";
        if (type.StartsWith("const ", StringComparison.Ordinal))
        {
            prefix = "const ";
            type = type["const ".Length..].TrimStart();
        }

        var dot = type.LastIndexOf('.');
        return prefix + (dot < 0 ? type : type[(dot + 1)..]);
    }

    private static string LowerDeclaration(string type, string name, string? selfType = null)
        => s_abiNames.LowerDeclaration(type, name, selfType);

    private static string LowerDeclaration(TypeNode? typeNode, string fallbackType, string name, string? selfType = null) =>
        s_abiNames.LowerDeclaration(typeNode, fallbackType, name, selfType);

    private static string LowerParameterDeclaration(ParameterNode parameter, string? selfType = null) =>
        s_abiNames.LowerParameterDeclaration(parameter, ParameterTypeText(parameter), selfType);

    private static string LowerFunctionTypeParameter(string parameter, string? selfType = null) =>
        s_abiNames.LowerFunctionTypeParameter(parameter, selfType);

    private static string SubstituteSelfType(string type, string? selfType) =>
        CTypeLowerer.SubstituteSelfType(type, selfType);

    private static string? ResolveSelfType(FunctionNode function)
    {
        if (FunctionOwnerTypeText(function) is not { } ownerType)
        {
            return null;
        }

        var typeArguments = FunctionTypeArgumentTexts(function);
        if (typeArguments.Count > 0)
        {
            return ResolveAdapterStorageType($"{ownerType}<{string.Join(",", typeArguments)}>");
        }

        var selfParameter = function.Parameters.FirstOrDefault(parameter => parameter.Name == "self");
        if (selfParameter is not null && !Regex.IsMatch(selfParameter.TypeNode.ToTypeName(), @"\bSelf\b"))
        {
            return NormalizeType(selfParameter.TypeNode.ToTypeName());
        }

        return ResolveAdapterStorageType(ownerType);
    }

    private static string? ResolveSelfApiType(FunctionNode function)
    {
        if (FunctionOwnerTypeText(function) is not { } ownerType)
        {
            return null;
        }

        var typeArguments = FunctionTypeArgumentTexts(function);
        return typeArguments.Count > 0
            ? $"{ownerType}<{string.Join(",", typeArguments)}>"
            : ownerType;
    }

    private static string NormalizeType(string type) => CTypeLowerer.NormalizeType(type);

    private static string RemovePointer(string type) => CTypeLowerer.RemovePointer(type);

    private static string? UnwrapPointer(string type)
    {
        type = type.Trim();
        return type.EndsWith("*", StringComparison.Ordinal)
            ? type[..^1].TrimEnd()
            : null;
    }

    private static bool TryParseGenericUse(string type, out string name, out IReadOnlyList<string> arguments)
        => CTypeLowerer.TryParseGenericUse(type, out name, out arguments);

    private static string SanitizeTypeName(string type) =>
        s_abiNames.SanitizeTypeName(type);

    private static bool TryParseFunctionType(
        string type,
        out IReadOnlyList<string> parameters,
        out string returnType)
        => CTypeLowerer.TryParseFunctionType(type, out parameters, out returnType);

    private static bool ReferencesCompositeType(string type, IReadOnlySet<string> compositeTypeNames)
        => CTypeLowerer.ReferencesCompositeType(type, compositeTypeNames, s_typeAdapters);

    private static IReadOnlyList<StructNode> OrderStructsByFieldDependencies(IReadOnlyList<StructNode> structs)
    {
        var remaining = structs.ToList();
        var remainingNames = remaining
            .Select(structNode => structNode.Name)
            .ToHashSet(StringComparer.Ordinal);
        var ordered = new List<StructNode>();

        while (remaining.Count > 0)
        {
            var index = remaining.FindIndex(structNode =>
                !structNode.Fields.Any(field => ReferencesCompositeType(StructFieldTypeText(field), remainingNames)));
            if (index < 0)
            {
                ordered.AddRange(remaining);
                break;
            }

            var next = remaining[index];
            ordered.Add(next);
            remaining.RemoveAt(index);
            remainingNames.Remove(next.Name);
        }

        return ordered;
    }

    private static bool UsesNull(ProgramNode program) =>
        program.GlobalVariables.Any(global => ContainsNull(global.Initializer))
        || program.Functions.Any(function => function.Body.Any(StatementUsesNull));

    private static bool StatementUsesNull(StatementNode statement) => statement switch
    {
        LetStatement let => ContainsNull(let.Initializer),
        ReturnStatement ret => ContainsNull(ret.Expression),
        CStatement c => ContainsNull(c.Expression),
        IfStatement ifStatement => ContainsNull(ifStatement.Condition)
            || ifStatement.ThenBody.Any(StatementUsesNull)
            || (ifStatement.ElseBranch is not null && StatementUsesNull(ifStatement.ElseBranch)),
        ElseBlockStatement elseBlock => elseBlock.Body.Any(StatementUsesNull),
        WhileStatement whileStatement => ContainsNull(whileStatement.Condition)
            || whileStatement.Body.Any(StatementUsesNull),
        ForStatement forStatement => ContainsNull(forStatement.Initializer)
            || ContainsNull(forStatement.CachedRangeEndInitializer)
            || ContainsNull(forStatement.CounterInitializer)
            || ContainsNull(forStatement.Condition)
            || ContainsNull(forStatement.Increment)
            || ContainsNull(forStatement.CounterIncrement)
            || forStatement.Body.Any(StatementUsesNull),
        SwitchStatement switchStatement => ContainsNull(switchStatement.Expression)
            || switchStatement.Cases.Any(switchCase =>
                ContainsNull(switchCase.Pattern) || switchCase.Body.Any(StatementUsesNull))
            || switchStatement.DefaultBody.Any(StatementUsesNull),
        _ => false,
    };

    private static bool ContainsNull(ForInitializerNode? initializer) => initializer switch
    {
        ForDeclarationInitializerNode declaration => ContainsNull(declaration.Initializer),
        ForExpressionInitializerNode expression => ContainsNull(expression.Expression),
        _ => false,
    };

    private static bool ContainsNull(ExpressionNode? expression) =>
        expression is not null && ContainsNull(expression.SourceText);

    private static bool ContainsNull(string? expression) =>
        expression is not null && Regex.IsMatch(expression, @"\bnull\b");

    private static string ExpressionText(ExpressionNode expression) => expression.SourceText;

    private sealed record InterfaceImplementation(StructNode Struct, InterfaceNode Interface);

    private sealed record ResolvedAdapterExpose(
        string BaseType,
        string BaseOwner,
        string SourceName,
        IReadOnlyList<string> TypeArguments);

    private sealed record AdapterExposeInfo(
        string AdapterName,
        IReadOnlyList<string> TypeParameters,
        string BaseType,
        bool IsStatic,
        string SourceName,
        string ExposedName,
        string? ReturnType);

    private sealed record GenericCallInfo(
        string? OwnerType,
        string Name,
        IReadOnlyList<string> TypeArguments,
        IReadOnlyList<string> ParameterTypes,
        string ReturnType,
        string CName,
        bool TakesPointerSelf,
        bool IsStatic);

}
